create table COMPONENT_ITEM_TYPE_FIELD_Q
(
    item integer not null,
    field integer not null
);

/*
 Field codes:
 1: Shorthand
 2: URI
 3: URL
 4: Cross Origin
 5: Integrity (as value)
 6: Integrity (as generator)
 7: Media (CSS)
 8: Local file upload
 9: Local Options
 10: Remote options
 */

INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (2, 1);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (2, 2);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (2, 4);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (2, 6);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (2, 7);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (2, 8);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (2, 9);

INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (3, 1);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (3, 3);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (3, 4);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (3, 5);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (3, 7);

INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (4, 1);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (4, 2);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (4, 4);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (4, 6);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (4, 8);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (4, 9);

INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (5, 1);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (5, 3);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (5, 4);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (5, 5);

INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (6, 1);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (6, 2);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (6, 4);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (6, 6);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (6, 8);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (6, 9);

INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (12, 1);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (12, 2);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (12, 4);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (12, 6);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (12, 8);
INSERT INTO COMPONENT_ITEM_TYPE_FIELD_Q (item, field) VALUES (12, 9);